version: '3.3'

services:
  users-db:
    container_name: usersdb
    image: postgres
    ports:
      - 5432:5432
    environment: 
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
          - db-data:/data/db
    networks:
      - bookstore-users

  users-app:
    container_name: users-app
    image: brujokan/bookstore-users:1.0.0
    ports: 
      - 8080:8080
    networks:
      - bookstore-users

networks:
    bookstore-users:

volumes:
  db-data: